routes/web.php
<?php

Auth::routes();

Route::group(['middleware' => ['auth']], function () {

	Route::get('/', 'HomeController@index')->name('dashboard');
	Route::get('/logout', 'HomeController@getLogout')->name('logout');
    Route::resource('user', 'UserController');
    Route::resource('aluno', 'Pando\StudentController');
    Route::resource('curso', 'Pando\CourseController');
	Route::get('certificado/{student}/{course}', 'Pando\StudentController@pdf')->name('certificado');

});

app/Http/Controllers/Pando/StudentController.php
<?php

namespace App\Http\Controllers\Pando;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Pando\Student;
use App\Pando\Course;
use App\Pando\CourseStudent;
use PDF;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $students = Student::all();
      return view('student.list', compact('students'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $courses = Course::all();
      return view('student.register',compact('courses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $student = Student::create($request->all());
      foreach ($request->course as $course) {
        CourseStudent::create([
            'student_id' => $student->id,
            'course_id' => $course
        ]);
    }
      return redirect()->route('aluno.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $student = Student::find($id);
      return view('student.details', compact('student'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $student = Student::find($id);
      $courses = Course::all();
      return view('student.alter', compact('student','courses'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $student = Student::find($id);
      $student->update($request->all());
      foreach ($request->course as $course) {
        CourseStudent::updateOrCreate([
          'student_id' => $id,
          'course_id' => $course
        ]);
      }
      return view('student.details', compact('student'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $student = Student::find($id)->delete();;
      return redirect()->route('aluno.index');
    }


    public function pdf(Request $request){
        $student = Student::find($request->student);
        $course = Course::find($request->course);

		$pdf = PDF::loadView('certified.certified',compact('student','course'));
		$pdf->setPaper('a4','landscape');
		return $pdf->stream();
        // return view("certified.certified");
    }
}

resources/views/student/alter.blade.php
@extends('layouts.theme')
@section('content')
{{Breadcrumbs::render('student-edit',$student)}}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <form method="POST" action="{{route ('aluno.update',$student->id)}}">
        @csrf
        @method('PATCH')
        <div class="card">
          <div class="card-header">
            <h1 class="title">{{__('Alterar Aluno')}}</h1>
          </div>
          <div class="card-body">
            <div class="form-row" id="form">
              <div class="form-group col-md-12">
                {!!Form::label('name', 'Nome:')!!}
                {!!Form::text('name', $student->name,['class'=>'form-control'])!!}
              </div>
              <div class="form-group col-md-12">
                <h1 class="title">Cursos Inscritos</h1>
              </div>

              @foreach($courses as $course)
              <div class="form-group col-md-4">
                <label>
                  <input class="" type="checkbox" name="course[]"
                  @foreach ($student->courses as $ver)
                  {{$course->verification($ver->id)}}
                  @endforeach
                  value="{{$course->id}}">
                  {{$course->name}}
                </label>
              </div>
              @endforeach

            </div>
          </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-dash float-right">Alterar</button>
            <a href="{{ route('aluno.index') }}" class="btn btn-dash float-left">
              <i class="fas fa-arrow-left"></i>
            </a>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
@endsection

resources/views/student/details.blade.php
@extends ('layouts.theme')
@section('content')
{{Breadcrumbs::render('student-show',$student)}}
<div class="container-fluid">
  {{-- Details --}}
  <div class="row">
    <div class="col-md-12">
      <div class="card mb-3">
        <div class="card-header">
          <div class="row">
          <div class="col-md-8">
            <h1 class="title"><i class="fas fa-users"></i> {{$student->name}}</h1>
          </div>
          <div class="col-md-4">
            <a class="btn-del float-right" data-toggle="modal" data-target="#excluir{{$student->id}}" href="#" title="Excluir">
                <i class="fas fa-trash"></i>
              </a>
            <a class="btn-edit float-right mr-1" href="{{ route('aluno.edit',$student->id) }}" title="Alterar">
              <i class="fas fa-edit"></i>
            </a>
            <a href="{{ route('aluno.index') }}" class="btn-dash float-right mr-1" title="Voltar">
              <i class="fas fa-arrow-left"></i>
            </a>
          </div>
          </div>
        </div>
        <div class="card-body">
          <div class="row">

            <div class="col-md-12">
              <div class="line-chart">
                <small>Nome</small>
                <p>{{$student->name }}</p>
              </div>
            </div>

            <div class="col-md-12 mt-3">
              <h1 class="title">Cursos Inscritos</h1>
            </div>

            @foreach ($student->courses as $course)
            <div class="col-md-4">
              <div class="line-chart">
                <p>{{$course->name }}</p>
                <small>{{$course->time }}</small>
                <a href="{{ route('certificado',[$student->id,$course->id]) }}" target="_blank">Certificado</a>
              </div>
            </div>
            @endforeach

          </div>

        </div>
      </div>
    </div>
  </div>
  {{-- End Details --}}


  {{-- Card Services --}}

</div>
@component('extends.modal')
  @slot('link')
    {{ route('aluno.destroy',$student->id) }}
  @endslot
  @slot('text')
    Tem certeza que deseja excluir ?
  @endslot
  @slot('id')
    {{$student->id}}
  @endslot
@endcomponent

@endsection

resources/views/student/list.blade.php
@extends ('layouts.theme')
@section('content')
{{Breadcrumbs::render('student')}}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        {{-- Header Card --}}
        <div class="card-header">
          <div class="row">
            <div class="col-md-8">
              <h1 class="title">{{ __('Lista de Alunos') }}</h1>
            </div>
            <div class="col-md-4">
              <a href="{{ route('aluno.create') }}" class="btn btn-create float-right">
                <i class="fas fa-plus"></i> Alunos
              </a>
            </div>
          </div>
        </div>
        {{-- End --}}
        {{-- Body Card --}}
        <div class="card-body">
          <div class="table-responsive">
            {{-- Table --}}
            <table id="datatable" class="table table-hover">
              <thead>
                <tr>
                  <th scope="col">Nome</th>
                  <th scope="col">Ações</th>
                </tr>
              </thead>
              <tbody>
                @forelse ($students as $student)
                <tr>
                  <td>{{$student->name }}</td>
                  <td>
                    <a class="btn-view" href="{{ route('aluno.show',$student->id) }}" title="Visualizar">
                      <i class="fas fa-search"></i>
                    </a>
                    <a class="btn-edit" href="{{ route('aluno.edit',$student->id) }}" title="Alterar">
                      <i class="fas fa-edit"></i>
                    </a>
                    <a class="btn-del" data-toggle="modal" data-target="#excluir{{$student->id}}" href="#" title="Excluir">
                      <i class="fas fa-trash-alt"></i>
                    </a>
                  </td>
                </tr>
                @empty

                <tr>
                  <td colspan="5">Nenhum registro encotrado!</td>
                </tr>
                @endforelse
              </tbody>
            </table>
            {{-- End table --}}
          </div>
        </div>
        {{-- End --}}
      </div>
    </div>
  </div>
</div>

@foreach ($students as $student)
@component('extends.modal')
@slot('link')
  {{ route('aluno.destroy',$student->id) }}
@endslot
@slot('text')
  Tem certeza que deseja excluir ?
@endslot
@slot('id')
  {{$student->id}}
@endslot
@endcomponent
@endforeach



@endsection

resources/views/student/register.blade.php
@extends('layouts.theme')
@section('content')
{{Breadcrumbs::render('student')}}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <form method="POST" action="{{route ('aluno.store')}}">
        @csrf
        <div class="card">
          <div class="card-header">
            <h1 class="title">{{__('Cadastro de Aluno')}}</h1>
          </div>
          <div class="card-body">
            <div class="form-row" id="form">
              <div class="form-group col-md-12">
                {!!Form::label('name', 'Nome:')!!}
                {!!Form::text('name', null,['class'=>'form-control'])!!}
              </div>
              <div class="form-group col-md-12">
                <h1 class="title">Cursos Inscritos</h1>
              </div>
              @foreach($courses as $course)
              <div class="form-group col-md-4">
                {!!Form::checkbox('course[]',$course->id)!!}
                {!!Form::label('course[]',$course->name)!!}
              </div>
              @endforeach
            </div>
          </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-dash float-right">Cadastrar</button>
            <a href="{{ route('aluno.index') }}" class="btn btn-dash float-left">
              <i class="fas fa-arrow-left"></i>
            </a>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
@endsection