routes/web.php
<?php

Auth::routes();

Route::group(['middleware' => ['auth']], function () {

	Route::get('/', 'HomeController@index')->name('dashboard');
	Route::get('/logout', 'HomeController@getLogout')->name('logout');
    Route::resource('user', 'UserController');
    Route::resource('aluno', 'Pando\StudentController');
    Route::resource('curso', 'Pando\CourseController');
	Route::get('certificado/{student}/{course}', 'Pando\StudentController@pdf')->name('certificado');

});

app/Http/Controllers/Pando/CourseController.php
<?php

namespace App\Http\Controllers\Pando;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Pando\Course;

class CourseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $courses = Course::all();
      return view('course.list', compact('courses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('course.register');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      Course::create($request->all());
      return redirect()->route('curso.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $course = Course::find($id);
      return view('course.details', compact('course'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $course = Course::find($id);
      return view('course.alter', compact('course'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $course = Course::find($id);
      $course->update($request->all());
      return redirect()->route('curso.show', compact('course'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $course = Course::find($id)->delete();
      return redirect()->route('curso.index');
    }
}

resources/views/course/alter.blade.php
@extends('layouts.theme')
@section('content')
{{Breadcrumbs::render('course-edit',$course)}}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <form method="POST" action="{{route ('curso.update',$course->id)}}">
        @csrf
        @method('PATCH')
        <div class="card">
          <div class="card-header">
            <h1 class="title">{{__('Alterar Curso')}}</h1>
          </div>
          <div class="card-body">
            <div class="form-row" id="form">
              <div class="form-group col-md-8">
                {!!Form::label('name', 'Nome:')!!}
                {!!Form::text('name', $course->name,['class'=>'form-control'])!!}
              </div>
              <div class="form-group col-md-4">
                {!!Form::label('time', 'Carga Horária:')!!}
                {!!Form::text('time', $course->time,['class'=>'form-control'])!!}
              </div>

            </div>
          </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-dash float-right">Alterar</button>
            <a href="{{ route('curso.index') }}" class="btn btn-dash float-left">
              <i class="fas fa-arrow-left"></i>
            </a>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
@endsection

resources/views/course/details.blade.php
@extends ('layouts.theme')
@section('content')
{{Breadcrumbs::render('course-show',$course)}}
<div class="container-fluid">
  {{-- Details --}}
  <div class="row">
    <div class="col-md-12">
      <div class="card mb-3">
        <div class="card-header">
          <div class="row">
          <div class="col-md-8">
            <h1 class="title"><i class="fas fa-users"></i> {{$course->name}}</h1>
          </div>
          <div class="col-md-4">
            <a class="btn-del float-right" data-toggle="modal" data-target="#excluir{{$course->id}}" href="#" title="Excluir">
                <i class="fas fa-trash"></i>
              </a>
            <a class="btn-edit float-right mr-1" href="{{ route('curso.edit',$course->id) }}" title="Alterar">
              <i class="fas fa-edit"></i>
            </a>
            <a href="{{ route('curso.index') }}" class="btn-dash float-right mr-1" title="Voltar">
              <i class="fas fa-arrow-left"></i>
            </a>
          </div>
          </div>
        </div>
        <div class="card-body">
          <div class="row">

            <div class="col-md-8">
              <div class="line-chart">
                <small>Nome</small>
                <p>{{$course->name }}</p>
              </div>
            </div>
            <div class="col-md-4">
                <div class="line-chart">
                  <small>Carga Horária</small>
                  <p>{{$course->time }}</p>
                </div>
              </div>
          </div>

        </div>
      </div>
    </div>
  </div>
  {{-- End Details --}}


  {{-- Card Services --}}

</div>
@component('extends.modal')
  @slot('link')
    {{ route('curso.destroy',$course->id) }}
  @endslot
  @slot('text')
    Tem certeza que deseja excluir ?
  @endslot
  @slot('id')
    {{$course->id}}
  @endslot
@endcomponent

@endsection

resources/views/course/list.blade.php
@extends ('layouts.theme')
@section('content')
{{Breadcrumbs::render('course')}}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        {{-- Header Card --}}
        <div class="card-header">
          <div class="row">
            <div class="col-md-8">
              <h1 class="title">{{ __('Lista de Cursos') }}</h1>
            </div>
            <div class="col-md-4">
              <a href="{{ route('curso.create') }}" class="btn btn-create float-right">
                <i class="fas fa-plus"></i> Curso
              </a>
            </div>
          </div>
        </div>
        {{-- End --}}
        {{-- Body Card --}}
        <div class="card-body">
          <div class="table-responsive">
            {{-- Table --}}
            <table id="datatable" class="table table-hover">
              <thead>
                <tr>
                  <th scope="col">Nome</th>
                  <th scope="col">Carga Horária</th>
                  <th scope="col">Ações</th>
                </tr>
              </thead>
              <tbody>
                @forelse ($courses as $course)
                <tr>
                  <td>{{$course->name }}</td>
                  <td>{{$course->time }}</td>
                  <td>
                    <a class="btn-view" href="{{ route('curso.show',$course->id) }}" title="Visualizar">
                      <i class="fas fa-search"></i>
                    </a>
                    <a class="btn-edit" href="{{ route('curso.edit',$course->id) }}" title="Alterar">
                      <i class="fas fa-edit"></i>
                    </a>
                    <a class="btn-del" data-toggle="modal" data-target="#excluir{{$course->id}}" href="#" title="Excluir">
                      <i class="fas fa-trash-alt"></i>
                    </a>
                  </td>
                </tr>
                @empty

                <tr>
                  <td colspan="5">Nenhum registro encotrado!</td>
                </tr>
                @endforelse
              </tbody>
            </table>
            {{-- End table --}}
          </div>
        </div>
        {{-- End --}}
      </div>
    </div>
  </div>
</div>

@foreach ($courses as $course)
@component('extends.modal')
@slot('link')
  {{ route('curso.destroy',$course->id) }}
@endslot
@slot('text')
  Tem certeza que deseja excluir ?
@endslot
@slot('id')
  {{$course->id}}
@endslot
@endcomponent
@endforeach



@endsection

resources/views/course/register.blade.php
@extends('layouts.theme')
@section('content')
{{Breadcrumbs::render('student')}}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <form method="POST" action="{{route ('curso.store')}}">
        @csrf
        <div class="card">
          <div class="card-header">
            <h1 class="title">{{__('Cadastro de Curso')}}</h1>
          </div>
          <div class="card-body">
            <div class="form-row" id="form">
              <div class="form-group col-md-8">
                {!!Form::label('name', 'Nome:')!!}
                {!!Form::text('name', null,['class'=>'form-control'])!!}
              </div>
              <div class="form-group col-md-4">
                {!!Form::label('time', 'Carga horária:')!!}
                {!!Form::text('time', null,['class'=>'form-control'])!!}
              </div>
            </div>
          </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-dash float-right">Cadastrar</button>
            <a href="{{ route('curso.index') }}" class="btn btn-dash float-left">
              <i class="fas fa-arrow-left"></i>
            </a>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
@endsection